-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

USE CATALOG `lakehouse`;
USE SCHEMA `nithya`;

-- COMMAND ----------

SELECT * from samples.wanderbricks.users

-- COMMAND ----------

select * from read_files("abfss://raw@adlsnaval123.dfs.core.windows.net/ecom/sales")

-- COMMAND ----------

create schema lakehouse.yourname managed location 'abfss://raw@adlsnaval123.dfs.core.windows.net/lakehouse/yourname'

-- COMMAND ----------

create schema lakehouse.nithya_bronze managed location 'abfss://raw@adlsnaval123.dfs.core.windows.net/lakehouse/nithya_bronze'

-- COMMAND ----------

create schema lakehouse.nithya_silver managed location 'abfss://raw@adlsnaval123.dfs.core.windows.net/lakehouse/nithya_silver'

-- COMMAND ----------

create schema lakehouse.nithya_gold managed location 'abfss://raw@adlsnaval123.dfs.core.windows.net/lakehouse/nithya_gold'
